### ISSUE TITLE
Uninitialized string offset: 0

### ISSUE THREAD

**Issue by iGavrilo** [nextras/migrations#102]
Hey, 

I think i found a bug. In new project (Nette sandbox) I installed nextras/migrations, add configuration in config.neon and migrations folder. If i want execute migrations I get a error.

Error:
Uninitialized string offset: 0

Stack trace:
https://www.dropbox.com/s/pxv5moo3ud14pqh/exception--2019-06-22--22-53--1a67a46997.html?dl=0

Version: 3.1

Problem with regex probably ? 

Thanks

**Comment by JanTvrdik** [comment]
Thank you for report. Can you check that it's fixed in `dev-master`?

**Comment by iGavrilo** [comment]
@JanTvrdik Its working :)

**Comment by JanTvrdik** [comment]
Released as version [3.1.1](https://github.com/nextras/migrations/releases/tag/v3.1.1)
