### ISSUE TITLE
Option to turn off order check

### ISSUE THREAD

**Issue by lupo112** [nextras/migrations#115]
Is it possible to add option to skip migrations order check?

We have multiple environments where db can be in different states. After merging and running migrations is not possible to rename them, because other environment would have problems with that. It would be great option to disable this check in cases where migrations not dependend on previous.

**Comment by hrach** [comment]
This is rather a unique feature and safe check we aim for. Probably could be avoided by creating custom groups for specific independent parts of the app. Isn't that a solution which would at least partially fit your needs?

**Comment by lupo112** [comment]
Hmmm, may be possible.
Can you provide some example?

**Comment by hrach** [comment]
See doc https://nextras.org/migrations/docs/3.2/nette-extension

**Comment by hrach** [comment]
Groups have defined dependencies. If they are independent, it allow you to migrate the app parts independently. Ordering is checked only in set of dependent groups.

**Comment by lupo112** [comment]
Seems like usable solution.
I did know this can be done using groups. Awesome!

Thanks!
