### ISSUE TITLE
ENUM in migrations

### ISSUE THREAD

**Issue by KarelWintersky** [nextras/migrations#118]
Does this package supports:

- renaming ENUM columns
- changing ENUM fields set

in migrations?

**Comment by mabar** [comment]
Migrations are just regular .sql files so yes, any sql compatible with your database is supported.

**Comment by KarelWintersky** [comment]
can I create this files with nextras/dbal ? On the fly, I mean

**Comment by hrach** [comment]
No, we do not have any autogeneration of the migration.

**Comment by KarelWintersky** [comment]
Sorry, what does auto generation have to do with it? I asked if your package supports SQL Enum?

**Comment by domainfun** [comment]
@KarelWintersky asked today:
> Sorry, what does auto generation have to do with it? I asked if your package supports SQL Enum?

As far as I can see, your question was answered in July 2021:
> Migrations are just regular .sql files so yes, any sql compatible with your database is supported.

This means if your database server supports ENUM you can put ENUM changes in an SQL file & use it, right?

You later asked:
> can I create this files with nextras/dbal ? On the fly, I mean

To me, "on the fly" sounds like you're expecting some sort of auto-generation of schema changes, hence today the reply was:
> No, we do not have any autogeneration of the migration.

What are we missing?
