### ISSUE TITLE
Undefined constant "Nextras\Migrations\Printers\STDOUT"

### ISSUE THREAD

**Issue by radimvaculik** [nextras/migrations#135]
Po upgrade na verzi 3.3.0, kde byla změněna funkce `detectColorSupport` v souboru `Printers\Console.php`, se zobrazuje chyba Undefined constant "Nextras\Migrations\Printers\STDOUT".

**Comment by JanTvrdik** [comment]
Are you running migrations in non-CLI SAPI?

**Comment by radimvaculik** [comment]
@JanTvrdik I use Console printer out of Console.
