### ISSUE TITLE
Doctrine DBAL, locks

### ISSUE THREAD

**Issue by solcik** [nextras/migrations#14]
Hello,

I just tried your v3 migrations with Doctrine DBAL and I ran into few problems:

The main one:

Query is returning string "1" and therefore it is going to throw error LockException('Unable to release a lock.'); from unlock method because in lock method is LockException('Unable to acquire a lock.'); thrown and that one is catched in run method of Runner.

![migrations-lock](https://cloud.githubusercontent.com/assets/1543737/7030129/afca6dc4-dd62-11e4-8b77-2690f076d2c7.PNG)
![migrations-unlock](https://cloud.githubusercontent.com/assets/1543737/7030132/b1f4452a-dd62-11e4-9010-5ebdc9c531d1.PNG)

**Comment by hrach** [comment]
<offtopic> inline variable viewer in phpstorm 9 is awesome </offtopic>

Thank you for the report. What are the others problems? :)

**Comment by solcik** [comment]
Just that, it is screeming, if folders are not created - I have just created structure folder, created migration, wanted to run that with migrations:reset and it throws an error that basic-data and dummy-data folders were not found.

**Comment by JanTvrdik** [comment]
It works fine for me – http://screencast.com/t/GUu5YulB when I run the tests. How does your Doctrine configuration differ from what we [have in tests](https://github.com/nextras/migrations/blob/e4658dc603c010e2768301cc4374d662c4bef161/tests/inc/IntegrationTestCase.php#L138-L149)?

**Comment by JanTvrdik** [comment]
Omg, bug in tests, missing `return` in https://github.com/nextras/migrations/blob/e4658dc603c010e2768301cc4374d662c4bef161/tests/inc/IntegrationTestCase.php#L143

**Comment by solcik** [comment]
I overlooked that too, when I looked into them and was just testing different drivers.

**Comment by JanTvrdik** [comment]
Is there an easy way to tell Doctrine to return correct data types?

**Comment by solcik** [comment]
Sorry, I do not use Doctrine DBAL directly, so I do not know, ORM is taking care of this ./

**Comment by JanTvrdik** [comment]
The way I see it – we can either change dependency from doctrine/dbal to doctrine/doctrine2 and use https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/NativeQuery.php which should [somehow](http://stackoverflow.com/questions/11483888/how-to-utilize-doctrine2-type-conversion-on-native-query-columns/11494408#11494408) support that or hack the conversions into `MySqlDriver`.

**Comment by solcik** [comment]
Thank you!
