### ISSUE TITLE
Wrong execution order of migrations

### ISSUE THREAD

**Issue by freezy-sk** [nextras/migrations#18]
Hi
When I try to run migrations with structure described down, I'm getting error because it's calling migrations in wrong order:
```
structures/2015-04-24-095312-init.sql
dummy-data/2015-07-14-153742-oauth2.sql
-error-
structures/2015-07-14-153742-oauth2.sql
```
Quickfix is to change `dummy-data/2015-07-14-153742-oauth2.sql` to time which is 1 second after file in structures, but this shows there is some other problem with ordering of migrations.

```
migrations
├── basic-data
├── dummy-data
│   ├── 2015-07-14-153742-oauth2.sql
├── structures
│   ├── 2015-04-24-095312-init.sql
│   └── 2015-07-14-153742-oauth2.sql
```

**Comment by Mikulas** [comment]
This seems intentional, dummy data group is alphabetically before structures group and will be run before structures group when name collision happens. https://github.com/nextras/migrations/blob/master/src/Engine/OrderResolver.php#L84

**Comment by hrach** [comment]
It makes sense, that if groups dependency tree is set correctly (dummy-data requires structures) to run structures earlier if there is timestamp/name match.

**Comment by JanTvrdik** [comment]
We should probably throw an exception if there are two migrations with identical logical names.

**Comment by freezy-sk** [comment]
@JanTvrdik Throwing exception does not make sense because migrations should be run in groups

**Comment by hrach** [comment]
Thanks for fix, @JanTvrdik !

**Comment by freezy-sk** [comment]
@JanTvrdik :+1:
