### ISSUE TITLE
Not possible to use without Symfony

### ISSUE THREAD

**Issue by sylvan-zd** [nextras/migrations#26]
Without installed Symfony\Console it crash on Bridges\SymfonyConsole\BaseCommand.php:22
Fatal Error Class 'Symfony\Component\Console\Command\Command' not found

**Comment by JanTvrdik** [comment]
Not true, it is entirely possible to use Nextras Migrations without Symfony, but you can't obviously use Symfony Command without Symfony.

See [documentation](http://nextras.org/migrations/docs/3.0/#toc-low-level-usage) on how to use Nextras Migrations without Symfony.
