### ISSUE TITLE
Automatically open editor when new migration created

### ISSUE THREAD

**Issue by Cactucs** [nextras/migrations#30]

**Comment by Mikulas** [comment]
Opening editors universally over all common operating systems if pretty involved.

I don't know if that is your use case, but at least the cli interface could be changed to return the path (currently it returns nothing).

Opening the file could then be as simple as (example for OS X)
```sh
c migrations:create structure foo | xargs open
-- or
c migrations:create structure foo | xargs open -a 'Sublime Text'
```

**Comment by Cactucs** [comment]
I'm on Ubuntu... So when it would return it would be:
```bash
xdg-open (c migrations:create structure foo)
```

Why it is for me a problem:
 - I don't have clickable paths in terminal (e.g. `git status`)
 - In PhpStorm takes indexing a long time... 

With returning path I would be able to create bash file - a alias to `c migrations:create` with `xdg-open`ing the output.

So +1 for returning
