### ISSUE TITLE
Fix master tests - postgre on php5.4 prefixes string

### ISSUE THREAD

**Issue by hrach** [nextras/migrations#37]
Have somebody any idea why postgre prefixes string on Php 5.4 with e? `e"string"` (I am not sure if it's the letter e, but something like this).

**Comment by JanTvrdik** [comment]
I remember @milo talking about something like that while ago in context of nette database but I could be wrong.

**Comment by Mikulas** [comment]
http://www.postgresql.org/docs/8.3/interactive/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS

> If the configuration parameter standard_conforming_strings is off, then PostgreSQL recognizes backslash escapes in both regular and escape string constants

http://www.postgresql.org/docs/8.3/interactive/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS

So maybe it could be fixed with
```sql
set standard_conforming_strings = on;
```
or `off`, I'm not sure ;)

**Comment by hrach** [comment]
The question is why it's affected only PHP 5.4?

**Comment by Mikulas** [comment]
Only relevant commit I could find is
https://github.com/php/php-src/commit/77d11b4959066dcbd47fce2ca65c41f5361ad40b

What version of 5.4 are you testing against?

**Comment by hrach** [comment]
thanks @JanTvrdik
