### ISSUE TITLE
Migration patches

### ISSUE THREAD

**Issue by Mikulas** [nextras/migrations#40]
Even though migrations should be immutable, in real life use there are often good reasons to change migrations.

There are many ways of solving this now:
- manually fix production databases :grimacing: 
- create patch sql file and manually run it on database server
- create a patch file and run it in deploy process automatically

The last option is actually pretty viable, but requires all users to implement it themselves (and nobody bothers, ending up fixing their databases manually).

Proposed feature: magic migration group `patches` that would contain file names in format `oldHash-newHash.extension`. Whenever OrderResolver finds hash collision, it would check if patch migration is defined. If so, it would prepend it to the migration queue and after executing it, it would automatically update `migrations` row with the `newHash`.

Those migrations would only be executed if both `oldHash` and `newHash` matched.

Different implementation could be executing a `patches` group (or any other name for that matter) prior to running "main" migrations. This is currently not possible due to the _Existing migrations depend on unknown group foo_ exception.

**Comment by hrach** [comment]
I don't see much added value in neither of the proposed solutions.

My current workflow is the following:

a) some query of the migration succeed:
  - update the rest of the migration & commit the changes
  - run the rest of the migration manually
  - update the hash in production database manually

b) none of queries succeeded:
  - update the whole migration
  - remove the migration entry on production

Thanks to your commit https://github.com/nextras/migrations/commit/52354b4e4225502a893c18280eef1e6c08643dda it's also super easy to change the hashes.

The need of patches shows there is something wrong in your process. I need it, personally, sometimes, but the need is not pretty small. From my point of view this is won't fix.

**Comment by Mikulas** [comment]
> My current workflow is the following: run the rest of the migration manually, update the hash in production database manually

That my point precisely. I assume we both agree there are very legitimate reasons to update old migrations.

I've actually managed to implement this without patching nextras migrations, but the code overhead is not negligible. https://gist.github.com/Mikulas/213604faa0b55e46588a I'm closing this as it's a wontfix for you anyway and opening #41 instead.
