### ISSUE TITLE
Refactor symfony commands to allow simpler overriding

### ISSUE THREAD

**Issue by Mikulas** [nextras/migrations#41]
Customizing commands is quite involved now: https://gist.github.com/Mikulas/213604faa0b55e46588a

Multiple properties should be protected instead of private, such as `BaseCommand:$dir` and `$driver`. Container extension could have a configuration option for custom command classes, for example in dictionary format `command-name: ClassName` which would also allow defining new commands.

**Comment by hrach** [comment]
Feel free to open pull-request with the private/protected. Some configuration of Symfony commands is needed, but probably request deeper changes, such as something like Configuration object.

**Comment by JanTvrdik** [comment]
[WIP long time ago](https://github.com/nextras/migrations/commit/46dbec336211b7691ed827d6c86042b68f1e621c)
