### ISSUE TITLE
Do not use constructor injection in Symfony command

### ISSUE THREAD

**Issue by JanTvrdik** [nextras/migrations#43]
We should avoid using constructor injection in Symfony command, because the command are not lazy loaded ([Symfony Console design problem](https://github.com/symfony/symfony/issues/12063)). Currently migrations + with all their dependencies need to be loaded every time any other unrelated command is executed.

Note that the solution should be ideally both Nette & Symfony compatible.

**Comment by Mikulas** [comment]
The only complex dependency of commands is currently `IDriver`. It does have a factory, so we could simply inject that instead, right?

**Comment by JanTvrdik** [comment]
IMHO we should replace the constructor with `injectDependencies(...)` method. It will work automatically with Kdyby Console and should add simple Symfony Bundle which would configure Symfony DI to call the method.

**Comment by hrach** [comment]
I do not like injectDependencies(). The bad design cannot be fixed with another bad design, factory seems much better to me.

**Comment by hrach** [comment]
But in this case, it's "just the commands"....

**Comment by JanTvrdik** [comment]
> The bad design cannot be fixed with another bad design,

Yes it can. 

---

The factory seems to me 

1. harder to implement because you cannot depend on specific container – we may need one factory for Nette and another one for Symfony
2. bad design as well
3. should be actually accessor (`get` method instead of `create`) – we don't need multiple driver instances

**Comment by hrach** [comment]
> harder to implement because you cannot depend on specific container – we may need one factory for Nette and another one for Symfony

Not at all. Just an interface. DI for Nette will handle this automatically, bundle for Symfony DI will somehow too. No difference to your solution. Only, it's a safer way how to do it.

**Comment by JanTvrdik** [comment]
I don't get how you implement it. AFAIK Symfony cannot generate automatic factory/accessor for interface.

**Comment by hrach** [comment]
The will be the task of that bundle, wouldn't be?

**Comment by JanTvrdik** [comment]
If by task you mean that in the `src/Bridges/Symfony` directory would by manually implemented `DriverAccessor` then yes.

I still prefer the simple `injectDependencies` method over solution with two extra files (`src/IDriverAccessor.php` + `src/Bridges/Symfony/DriverAccessor.php`).

**Comment by JanTvrdik** [comment]
fixed on Symfony side

**Comment by mabar** [comment]
Not really. Listing commands still create instances of all commands.

**Comment by JanTvrdik** [comment]
@mabar Yes, but that's not an issue in production. Also nextras migrations no longer connects to database in constructor.
