### ISSUE TITLE
Ignore missing directories

### ISSUE THREAD

**Issue by fabik** [nextras/migrations#46]
I am getting this error on CI, because basic-data directory does not exist. I am only using structures.

```
Directory "/home/ubuntu/wallet/tests/../app/../migrations/basic-data" does not exist.
```

Could you please ignore directories which do not exist?

**Comment by JanTvrdik** [comment]
I aware of such behavior and I'm still undecided whether ignoring the error is a good idea.

**Comment by CZechBoY** [comment]
+1
because you cannot simply commit empty directory to git repository. And what is difference between empty directory and non existimg directory?

**Comment by JanTvrdik** [comment]
Non-existing directory may indicate critical bug in you migrations. Ignoring the error may break you application.
