### ISSUE TITLE
Break support for LeanMapper

### ISSUE THREAD

**Issue by honzarac** [nextras/migrations#55]
After commit 1293b15 migrations not support LeanMapper\Connection and requires exact Dibi\Connection or Dibi\Connection.

It throws LogicException
Invalid argument, expected instance of Dibi\Connection or DibiConnection

https://github.com/nextras/migrations/commit/1293b15cea350cc6dc2a6536bf23dd56fecca11a#diff-52a4514d7808fcb11ac6bc6e7184bf67R25

**Comment by JanTvrdik** [comment]
@honzarac use Dibi2Adapter or Dibi3Adapter instead of DibiAdapter

**Comment by hrach** [comment]
Hm, the solution with direct adapter usage is ok. Still, I do not understand your question.
