### ISSUE TITLE
BUG Nextras\Migrations\Engine\Runner - Exception in method run not handled 

### ISSUE THREAD

**Issue by tomaskarlik** [nextras/migrations#62]
```php
try {
  // mehotd run
} catch (Exception $e) { 
}
```
may be ``` \Exception``` or ```use Exception``` and fix it in others method

**Comment by JanTvrdik** [comment]
That's likely intentional. Does it cause you any trouble?

**Comment by tomaskarlik** [comment]
Sorry, I was overlooked, ```Exception``` is interface of Nextras\Migrations\. I run migrations inside phpunit tests to create testing DB, and problem was here. Thanks.
