### ISSUE TITLE
Doctrine IDbal isn't lazy, Symfony commands starts db connection everytime.

### ISSUE THREAD

**Issue by hrach** [nextras/migrations#64]
Currently, Doctrine Adapter directly requires Doctrine Connection, which is not lazy; so every Symfony Command listing starts a database connection. (https://github.com/nextras/migrations/blob/master/src/Bridges/DoctrineDbal/DoctrineAdapter.php)

- should be this fixed for nextras migrations?
- should be this fixed on commands layer (e.g. commands should not instantiate required dependencies, until you run them)
- should be this fixed on adapter layer?

**Comment by JanTvrdik** [comment]
https://github.com/nextras/migrations/issues/43

**Comment by JanTvrdik** [comment]
The seems from a very fast glance similar to what I wanted to do https://github.com/fezfez/symfony-console-di

**Comment by hrach** [comment]
Updated initial comment, own lazy IDbal doesn't help, since driver calls dbal->escape*() which also initialize a connection.

**Comment by JanTvrdik** [comment]
should be solved by https://github.com/nextras/migrations/commit/36fd4b77c283064913eb80208ea219642dc29865
