### ISSUE TITLE
Symfony console not being loaded

### ISSUE THREAD

**Issue by dakorpar** [nextras/migrations#67]
Hi,
I get this exception
![screenshot_4](https://cloud.githubusercontent.com/assets/9303856/24243855/7c26f146-0fb4-11e7-9cfc-c023d248aebe.png)

it's solved if I add "symfony/console": "^3.2" manually to my composer, but IMHO this should NOT happen, and fix shouldn't be just installing console, but being able to work without it.
Any solutions?

**Comment by JanTvrdik** [comment]
That's an expected behavior. Symfony Console is an optional dependency.

**Comment by dakorpar** [comment]
It's happening as soon as I load any page, not using migrations at all...
![screenshot_4](https://cloud.githubusercontent.com/assets/9303856/24246515/93fc2952-0fbf-11e7-9a41-c6722c109715.png)

**Comment by ivanscm** [comment]
https://packagist.org/packages/symfony/console

**Comment by dakorpar** [comment]
@ivanscm please read issue. It's more then clear then adding this package solves issue, but since I'm not using it and it's optional it should work without it.
