### ISSUE TITLE
Whitelist of production database(s)

### ISSUE THREAD

**Issue by f3l1x** [nextras/migrations#70]
I have an idea about whitelisted database which will prevent of calling `migration:reset` command. Just for security reasons. What do you think?

**Comment by JanTvrdik** [comment]
> Whitelist of production database

I assume you mean whitelist of dev databases, otherwise it would useless.

---

The problem is that local database often has the same name as production database. Maybe would could create e.g. table `migrations_dev` on localhost and allow resetting database only when the table exists?

**Comment by f3l1x** [comment]
Something like that, I have not figured this out, just posting an idea. :-)

**Comment by Mikulas** [comment]
Yep, this is needed. This could probably best be implemented as a check against an environment variable. It probably should be an opt-in featured. The env name could be defined in the configuration.

Also it should be noted this is mostly preventing an user error and not adding very much “security”. With this in mind, the reset command could also ask for a nonce such as current datetime string.

**Comment by mabar** [comment]
I would like to add new configuration option to extension. Something like `registerResetCommand`. Simple, two lines of code solution.

**Comment by f3l1x** [comment]
Closing it, doesn't need it anymore.

**Comment by dakur** [comment]
@f3l1x Why have you closed this? There is similar issue #84 and it is not still resolved as there is still simple way to destroy whole production database in a moment. You don't want to allow such thing without any confirmation. Can we please reopen it and agree on some resolution?

**Comment by jkuchar** [comment]
Isn't it possible to just deregister the command from DI services?

**Comment by dakur** [comment]
Yes, use:

```neon
services:
	migrations.resetCommand: false
```

**Comment by jkuchar** [comment]
To be precise, we use a environment based config, that is loaded only in production environment, where it deregisters that command:

<img width="480" alt="image" src="https://github.com/nextras/migrations/assets/133822/9233bb3c-47f8-48ac-87fa-df0f2536ef10">
