### ISSUE TITLE
how to ignore Invalid default value for datetime

### ISSUE THREAD

**Issue by regiss** [nextras/migrations#77]
I have problem that our existing database tables have default value '0000-00-00 00:00:00' for datetime. Problem is that when altering table (for example adding new column 'test01' with type int) via migration script I get following error: 
**Invalid default value for 'field which is using datetime'**
Is there an option to ignore 'default values' for datetime ?

According to mysql docu, it should be possible to use sql_mode 'ALLOW_INVALID_DATES'
It seems to be problem related to MysqliDriver. I am using Nextras\Dbal\Connection

I can execute sql script via adminer without any problem, bot not through migration script

**Comment by JanTvrdik** [comment]
Just add `SET sql_mode = 'ALLOW_INVALID_DATES';` to the migration.

**Comment by regiss** [comment]
Thank you this worked.

**Comment by hrach** [comment]
Great, closing :)
