### ISSUE TITLE
Allow multiple independent extensions

### ISSUE THREAD

**Issue by webrouse** [nextras/migrations#94]
Hi,

Branch/commit: `master - 5970edad7945214a3eb5e22f74caa1cd35303b4d`.

I registered extension twice in my `config.neon`. 
Each instance for separated database, with separated migrations dir.
And it was working with some `3.0@dev` version.

Now I try to update to `3.1@dev` version.
**But migrations (dirs / ` Nextras\Migrations\Entities\Group`) from each separated extension are mixed together.** In each configuration (generated by extension) are present all groups.

Reason is probably in `MigrationsExtension::createConfigurationDefinition`. 
It creates `Nextras\Migrations\Configurations\Configuration` with autowired constructor paramater`Group[] $groups`.

The solution would be to provide constructor parameters of `Configuration` directly without autoloading. 

Version `v3.1.0-rc2` is working.

**Comment by o5** [comment]
@webrouse Did you use it with Symfony Command? How about console commands name prefix? https://github.com/nextras/migrations/blob/master/src/Bridges/SymfonyConsole/ContinueCommand.php#L20
