### ISSUE TITLE
Deprecated setDynamic na Nette 3+

### ISSUE THREAD

**Issue by hamtil** [nextras/migrations#97]
Nette\DeprecatedException: Service migrations.structureDiffGenerator: Nette\DI\Definitions\ServiceDefinition::setDynamic() is deprecated, use $builder->addImportedDefinition(...) in /srv/tetraedr/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php:158

#0 /srv/tetraedr/vendor/nextras/migrations/src/Bridges/NetteDI/MigrationsExtension.php(86): Nette\DI\Definitions\ServiceDefinition->setDynamic()

**Comment by JanTvrdik** [comment]
this should be fixed in master, i'll try to release new stable version soon

**Comment by hamtil** [comment]
I have it on version:
"nextras/migrations": "v3.1.0-rc5",

**Comment by JanTvrdik** [comment]
should be fixed in [3.1.0](https://github.com/nextras/migrations/releases/tag/v3.1.0)
